env: "local"
httpServer:
  host: "localhost"
  port: "8080"
  timeout: "4s"
  shutdownTimeout: "10s"
pg:
  login: "postgres"
  password: "Rtyuehe1223"
  host: "localhost"
  port: "5432"
  dbName: "wblevel0"
  sslMode: "disable"
  maxConn: 20
  minConn: 5
natsStream:
  clusterID: "test-cluster"
  clientID: "test-client"